### ISSUE TITLE
Upgrade for compatibility with new Datasette 1.0 JSON format

### ISSUE THREAD

**Issue by brandonrobertz** [simonw/datasette-search-all#19]
Running datasette, version 1.0a2 this plugin seems broken.

When the search runs, it always gets `undefined` for the row count from ` data.filtered_table_rows_count`.

https://github.com/simonw/datasette-search-all/blob/5b5f1926d7634ae3ed39f7eaf3fa74325e5d842b/datasette_search_all/templates/search_all.html#L127

I changed this to `data.count` and the plugin works as it used to.

**Comment by simonw** [comment]
I also got this error:

`TypeError: columns is undefined`

**Comment by simonw** [comment]
I think I need a Playwright test for this, since it's a bug in the JavaScript.

I'll borrow from https://github.com/datasette/datasette-comments/blob/a0f637f6a3d6927a00c678166d7e66363df1a7b5/tests/test_ui.py#L2

**Comment by simonw** [comment]
Here's the code that's failing: https://github.com/simonw/datasette-search-all/blob/3ecd8e6d6460f5a1802da42bc4c6f3b4628261b7/datasette_search_all/templates/search_all.html#L121-L126

I don't think I've exposed all of that stuff as `?_extra=` yet.

**Comment by simonw** [comment]
Actually I have: https://latest.datasette.io/fixtures/searchable.json?__search=dog&_extra=count&_extra=table&_extra=database&_extra=columns

```json
{
  "ok": true,
  "next": null,
  "columns": [
    "pk",
    "text1",
    "text2",
    "name with . and spaces"
  ],
  "database": "fixtures",
  "count": 2,
  "table": "searchable",
  "rows": [
    {
      "pk": "pk",
      "text1": "text1",
      "text2": "text2",
      "name with . and spaces": "name with . and spaces"
    },
    {
      "pk": "pk",
      "text1": "text1",
      "text2": "text2",
      "name with . and spaces": "name with . and spaces"
    }
  ],
  "truncated": false
}
```

**Comment by simonw** [comment]
Found a Datasette 1.0 bug: the `?_extra=columns` parameter causes all rows to return `"column-name": "column-name": https://latest.datasette.io/fixtures/attraction_characteristic.json?_extra=columns&_size=1
```json
{
  "ok": true,
  "next": "2,2",
  "columns": [
    "pk",
    "name"
  ],
  "rows": [
    {
      "pk": "pk",
      "name": "name"
    }
  ],
  "truncated": false
}
```
Should return this:
```json
{
  "ok": true,
  "next": "2,2",
  "columns": [
    "pk",
    "name"
  ],
  "rows": [
    {
      "pk": 2,
      "name": "Paranormal"
    }
  ],
  "truncated": false
}
```

**Comment by simonw** [comment]
That bug is a bit of a blocker on this task. For the moment I'll use the keys from the first returned row.

**Comment by simonw** [comment]
Got that working - the tests are a bit ugly in terms of Playwright boilerplate:

https://github.com/simonw/datasette-search-all/blob/502ac1eec5ec0df06ea65590eb66eca3389f0cc8/tests/test_playwright.py#L7-L24

Playwright includes `pytest` fixtures, you can use `page` to get a page to interact with.

I was getting "This event loop is already running" errors when I tried to use that, but it looks like the solution is to add `nest_asyncio.apply()` which seems to have fixed it.

- https://github.com/microsoft/playwright-python/issues/178

**Comment by simonw** [comment]
Much neater:

https://github.com/simonw/datasette-search-all/blob/e79f19a87ad6c93f2e4f57e19f6013a4e204033d/tests/test_playwright.py#L13-L23

**Comment by simonw** [comment]
Job matrix looks pretty good!

![CleanShot 2024-01-08 at 12 01 50@2x](https://github.com/simonw/datasette-search-all/assets/9599/34e166ea-05aa-4e83-ae24-de2a3fd82dda)

**Comment by simonw** [comment]
Tested this on Datasette Cloud as well.

**Comment by simonw** [comment]
I'm going to delete the `datasette-cloud-varnish` app: https://fly.io/apps/datasette-cloud-varnish

![CleanShot 2024-01-08 at 15 12 11@2x](https://github.com/simonw/datasette-search-all/assets/9599/ce8760f3-fd28-4555-bc51-55211aade2d0)
